config/routes.rb
ASCIIRubyTron::Application.routes.draw do
  root 'battlefield#index'

  post 'make_move' => 'battlefield#make_move'
  get 'quit_game' => 'battlefield#quit_game', as: 'quit_game'
  get 'start_game' => 'battlefield#start_game', as: 'start_game'
end

app/models/snake.rb
class Snake

  attr_reader :id
  attr_reader :snake_segments

  $SNAKE_COLORS = ['#FFA812', '#00FF00', '#007DFF', '#993366', '#F984E5', '#FF9900', '#000080', '#00FF7F', '#BADBAD']

  def initialize(id)
    @id = id
    @snake_segments = $redis.lrange("snake_#{id}", 0, -1)
  end

  def start!
    check_the_past
  end

  def move!(direction)
    if can_move?(direction)
      step(direction)
    else
      loose!
    end
  end

  def destroy!
    coordinates_for_destroy = @snake_segments.map {|e| e.split(',').map(&:to_i) }
    PrivatePub.publish_to "/destroy", segments: @snake_segments.map {|e| e.split(',').map(&:to_i) }
    $redis.del("snake_#{id}")
  end

  def loose!
    PrivatePub.publish_to "/game_over", player: @id
    destroy!
  end

private

  def check_the_past
    unless @id.present?
      previous_player_id = $redis.lindex('users', 0).to_i
      @id = previous_player_id + 1
      $redis.lpush "users", @id
      $redis.lpush "snake_#{@id}", ["0,#{@id * 3}"]
    end
  end


  def head_coordinates
    @snake_segments[0].split(',').map(&:to_i)
  end

  def can_move?(direction)
    new_head_coordinates = head_coordinates
    new_head_coordinates[0] += direction[0]
    new_head_coordinates[1] += direction[1]

    not_wall?(new_head_coordinates) && not_body?(new_head_coordinates)
  end

  def not_wall?(new_head_coordinates)
    new_head_coordinates.all?{|e| e >= 0 && e <= 99 }
  end

  def not_body?(new_head_coordinates)
    @snake_segments.all?{|e| e != "#{new_head_coordinates[0]},#{new_head_coordinates[1]}"}
  end

  def step(direction)
    new_head_coordinates = head_coordinates
    new_head_coordinates[0] += direction[0]
    new_head_coordinates[1] += direction[1]

    $redis.lpush "snake_#{@id}", "#{new_head_coordinates[0]},#{new_head_coordinates[1]}"

    PrivatePub.publish_to "/move",
      coordinates: new_head_coordinates,
      player: @id,
      color: $SNAKE_COLORS[@id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/battlefield_controller.rb
class BattlefieldController < ApplicationController
  before_filter :get_ready_snake!

  def index
    users = $redis.lrange('users', 0, -1)
    @before = []
    users.each {|u| @before += [ShowBefore.all(u)]}
    @current_player=current_player.to_i
  end

  def make_move
    @snake.move!(params[:direction].map(&:to_i))
    render nothing: true
  end

  def quit_game
    @snake.destroy!
    cookies[:player_number] = nil
    redirect_to root_path
  end

  def start_game
    @snake.start!
    cookies[:player_number] = @snake.id
    redirect_to root_path
  end

  private

    def get_ready_snake!
      @snake = Snake.new(cookies[:player_number])
    end

    def current_player
      cookies[:player_number]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def signed_in?
    cookies[:player_number].present?
  end
end

app/views/battlefield/index.html.slim
= subscribe_to "/move"
= subscribe_to "/destroy"
= subscribe_to "/game_over"

- if signed_in?
  = link_to 'Я идиот, убейте меня кто-нибудь11 (покинуть игру)', quit_game_path
- else
  = link_to 'В бой, змеевоен11 (начать игру)', start_game_path

.battlefield
  table.map frame='border' cellspacing="0" cellpadding="0"
    tbody
      -100.times do |y|
        tr
          -100.times do |x|
            td.cell id= "x#{x}y#{y}"
              -@before.each do |snake|
                -if snake.index("#{x},#{y}") != nil
                  span style= "color: #{$SNAKE_COLORS[@before.index(snake)]}"
                    = '¤'
                  - break

app/views/layouts/application.html.slim
doctype html
html lang="ru"
  head
    title ASCIIRubyTron
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true 
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    = yield